### ISSUE TITLE
runner_time doesn't work in OS X

### ISSUE THREAD

**Issue by stylemistake** [stylemistake/bash-task-runner#4]
Utility `date` in Mac OS X is not the same as `date` in `coreutils`. It doesn't support outputting current time in nanoseconds.

```
$ date +%s%N
1397392146%N
```

**Comment by Spaxe** [comment]
You can probably work around this by getting OS X users to install `coreutils`, which is listed as a requirement anyway.

Problem is, Homebrew installs GNU `date` as `gdate`, so you probably need an additional check.

See http://apple.stackexchange.com/questions/135742/time-in-milliseconds-since-epoch-in-the-terminal

**Comment by stylemistake** [comment]
@Spaxe Yeah, seems like the only good solution. I thought about not using nanoseconds at all, but cutting features away is not fun.

**Comment by Spaxe** [comment]
Just sent you a pull request. `date` on the OS X only gives you seconds, not milliseconds, so it still doesn't work currently. The patches in my pull request should work even with nanoseconds since it requires GNU `date`.
